In [14]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [15]:
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]

x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

print(x_train)
print(y_train)

tensor([[1., 2.],
        [2., 3.],
        [3., 1.],
        [4., 3.],
        [5., 3.],
        [6., 2.]])
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])


In [16]:
# 시그모이드 함수 정의 

def sigmoid(x):
    return 1/(1+torch.exp(-x))

In [21]:

# parameter 정의 h = sigmoid(w*x+b)
W = torch.zeros((2,1),requires_grad=True)
b = torch.zeros(1,requires_grad=True)

# optimizer
optimizer = optim.SGD([W,b],lr=1)


nb_epochs = 20000

for epoch in range(1,nb_epochs+1):
    
    
    Hx = sigmoid(x_train.matmul(W)+b) # 6 x 1 배열 
    
    cost = -(y_train * torch.log(Hx) + (1 - y_train) * torch.log(1 - Hx)).mean()
    cost2 = -torch.mean(y_train*torch.log(Hx)+(1-y_train)*torch.log(1-Hx))
    
    optimizer.zero_grad()
    cost2.backward()
    optimizer.step()
    
    if epoch%100==0:
        print("{}/{} cost: {} ".format(epoch,nb_epochs,cost2.item()))
    

100/20000 cost: 0.13564403355121613 
200/20000 cost: 0.08096423000097275 
300/20000 cost: 0.05806249380111694 
400/20000 cost: 0.04539801552891731 
500/20000 cost: 0.037327006459236145 
600/20000 cost: 0.03171999379992485 
700/20000 cost: 0.027591748163104057 
800/20000 cost: 0.024422310292720795 
900/20000 cost: 0.021910781040787697 
1000/20000 cost: 0.01987062394618988 
1100/20000 cost: 0.01817995309829712 
1200/20000 cost: 0.016755729913711548 
1300/20000 cost: 0.015539352782070637 
1400/20000 cost: 0.014488295651972294 
1500/20000 cost: 0.013570779003202915 
1600/20000 cost: 0.012763001024723053 
1700/20000 cost: 0.012046191841363907 
1800/20000 cost: 0.011405830271542072 
1900/20000 cost: 0.010830279439687729 
2000/20000 cost: 0.01031011063605547 
2100/20000 cost: 0.0098377401009202 
2200/20000 cost: 0.009406833909451962 
2300/20000 cost: 0.00901214499026537 
2400/20000 cost: 0.008649274706840515 
2500/20000 cost: 0.008314534090459347 
2600/20000 cost: 0.008004778064787388 
2700/2

In [19]:
print(sigmoid(x_train.matmul(W)+b))

tensor([[1.9086e-07],
        [1.7892e-03],
        [2.0913e-03],
        [9.9747e-01],
        [9.9999e-01],
        [1.0000e+00]], grad_fn=<MulBackward0>)
